#import "../../preamble.typ": *
#show: preamble
== 1.1 -- Algebras and $sigma$-Algebras
1.
  Find the $sigma$-algebra on $RR$ generated by all singletons.
  #sol[
    Let $Sigma$ denote this $sigma$-algebra. For countable $U subset.eq RR$,
      $
        U = union.big_(x in U) {x} in Sigma
      $
      so
      $
        Sigma = {U subset.eq RR mid(|) abs(U) <= aleph_0 or abs(RR without U) <= aleph_0}
      $
    #h(1fr)
  ]
2.
  Show that $scr(B)(RR)$ is generated by $cal(B) = {(-infinity, b]}_(b in QQ)$.
  #sol[
    For $a < b in RR$,
      $
        (a, b) = bp(RR without (-infinity, a]) inter union.big_(n in NN) (-infinity, b_n] in sigma(cal(B))
      $
      where $b_n$ is the decimal expansion of $b$ up to $n$ decimal places, so $sigma(B)$ contains all open sets and thus $scr(cal(B))(RR)$, and for $c in QQ$,
      $
        (-infinity, c] = inter.big_(n in NN) (-infinity, c + 2^(-n)) in scr(B)(RR)
      $
      so $sigma(cal(B)) = scr(B)(RR)$. #qed
  ]
3.
  Show that $scr(B)(RR)$ is generated by the set $cal(C)$ of compact subsets of $RR$.
  #sol[
    By the Bolzano-Weierstrass Theorem, the compact sets in $RR$ are those that are closed and bounded, and any closed $U subset.eq RR$ can be written as
      $
        U = union.big_(n in NN) bpp([U inter [-n, n]]) in sigma(cal(C))
      $
      so $scr(B)(RR) = sigma(cal(C))$. #qed
  ]
4.
  Show that if $cal(A)$ is an algebra of sets and all pairwise disjoint, countable $A subset.eq cal(A)$ have union in $cal(A)$, then $cal(A)$ is a $sigma$-algebra.
  #sol[
    For ${A_n}_(n in NN) subset.eq cal(A)$,
      $
        union.big_(n in NN) A_n = union.big_(n in NN)[A_n without union.big_(k = 0)^(n - 1) A_n] in cal(A)
      $
      #qed
  ]
5.
  Show by example that the union of a set of $sigma$-algebras on a set $X$ may not itself be a $sigma$-algebra.
  #sol[
    Consider the set $X = {1, 2, 3}$ and
      $
        Sigma_1 &= {emptyset, {1}, {2, 3}, X} \
        Sigma_2 &= {emptyset, {2}, {1, 3}, X}
      $
    Both $Sigma_1$ and $Sigma_2$ are $sigma$-algebras on $X$, but their union is not, as it does not contain ${3} = {1, 3} without {1}$. \ #qed
  ]
6.
  Find an infinite collection of subsets of $RR$ containing $RR$ which is closed under countable unions and intersections but is not a $sigma$-algebra.
  #sol[
    Consider the collection $cal(C) = {[-n, n]}_(n in NN)$. For ${n_k}_(k in NN) subset.eq NN$,
      $
        union.big_(k in NN) [-n_k, n_k] &= [-max_(k in NN)(n_k), max_(k in NN)(n_k)] in cal(C) \
        inter.big_(k in NN) [-n_k, n_k] &= [-min_(k in NN)(n_k), min_(k in NN)(n_k)] in cal(C) \
        RR &= union.big_(n in NN) [-n, n] in cal(C)
      $
      so $cal(C)$ is closed under countable unions and intersections and contains $RR$, but it does not contain the empty set and is thus not a $sigma$-algebra.
  ]
7.
  Let $scr(I) subset.eq cal(P)(X)$, and show that for all $A in sigma(scr(I))$, there is some countable $scr(C)_0 subset.eq scr(I)$ such that $A in sigma(scr(C)_0)$.
  #sol[
    Let
      $
        scr(A) = union.big {sigma(scr(C)) mid(|) NN prec.eq scr(C) subset.eq scr(I)}
      $
    $emptyset, X in sigma(scr(C))$ for any $scr(C) subset.eq scr(I)$, so $X in scr(A)$. For $U in scr(A)$, there is some countable $scr(C) subset.eq scr(I)$ with $U in sigma(scr(C))$, so $X without U in sigma(scr(C)) subset.eq scr(A)$. Let ${U_n}_(n in NN) subset.eq scr(A)$. For each $n in NN$, $U_n in sigma(scr(C)_n)$ for some countable $scr(C)_n subset.eq scr(I)$.
  ]
8.
  Find all $sigma$-algebras on $NN$.
  #sol[
    The set of $sigma$-algebras is given by
      $
        Omega &= {Sigma subset.eq cal(P)(NN) mid(|) emptyset, NN in Sigma; forall A in Sigma, NN without A in Sigma; NN prec.eq S subset.eq Sigma, union.big cal(S) in Sigma}
      $
  ]
9.
  #set enum(numbering: "(a)")
  1.
    Show #label("1.1.9.a") that $QQ$ is $"F"_sigma$ but not $"G"_delta$.
    #sol[
      $QQ$ is closed in $RR$ and thus trivially $"F"_sigma$.

      Suppose that $QQ$ is the intersection of some countable $cal(B) subset.eq cal(G)(RR)$. Then since $QQ$ is dense in $RR$, so is each $U in cal(B)$, as $QQ subset.eq U_n$. By De Morgan's Law,
        $
          RR without QQ = RR without union.big_(q in QQ) {q}
              = inter.big_(q in QQ) [RR without {q}]
        $
      $RR without QQ$ is thus the countable intersection of dense open sets, but
        $
          inter.big cal(B) inter.big_(q in QQ) [RR without {q}]
              = QQ inter (RR without QQ)
              = emptyset
        $
      This expresses the empty set as a countable intersection of dense open sets despite it not itself being dense in $RR$, violating the Baire Category Theorem. It therefore must not be the case that $QQ$ is not $"G"_delta$. #qed
    ]
  2.
    Find a subset of $RR$ that is neither $"F"_sigma$ nor $"G"_delta$.
    #sol[
      Let $A = (-infinity, 0) without QQ$, $B = (0, infinity) inter QQ$, and $C = A union B$. Then by #link(label("1.1.9.a"))[(a)], $A$ is $"G"_delta$  while $B$ is closed and thus $"F"_sigma$. If $C$ is $"F"_sigma$, then $A = C inter (-infinity, 0)$ is also $"F"_sigma$, while if $C$ is $"G"_delta$, then so is $B$. Both of these results contradict #link(label("1.1.9.a"))[(a)], so $C$ must be neither $"F"_sigma$ nor $"G"_delta$.
    ]
